# see https://pre-commit.com/ for detailed explanation
# pre-commit, once installed, runs scripts prior to each commit to enforce certain standards
# all hooks identified by `hooks: id:` syntax are run sequentially
# .pre-commit-config.yaml format identifies hooks by the repo they come from, version, and
# commands to run with optional arguments and exclusions
# currently this config runs
#     - 2 built-in hooks from the base pre-commit repo
#     - black, which autoformats python to a common standard
#     - flake8, which enforces PEP8 standards
#     - mypy, which enforces static type hints
#     - isort, which automatically sorts imports to PEP8 standard

# globally exclude all venv files from any hooks
exclude: ^(.venv*|venv*|scratch)
# specific hooks defined under repos
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        args: [--config=./pyproject.toml]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [--config=./.flake8]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        args: [--config-file=./pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--settings-path=./pyproject.toml]
